export const messages = [
    { "author": { "name": "Blazing", "profile": "discord_profile_1.png" }, "text": "Did you hear about the new Jurassic movie trailer?" },
    { "author": { "name": "GrandNerd", "profile": "discord_profile_3.png" }, "text": "Yeah! The dinosaurs look even more realistic this time!" },
    { "author": { "name": "Cryolexis", "profile": "discord_profile_2.png" }, "text": "I just hope they don’t make the same mistakes again." },
    { "author": { "name": "DinoDude32", "profile": "discord_profile_4.png" }, "text": "We all know someone’s gonna ignore safety protocols again." },
    { "author": { "name": "Spinosalad", "profile": "discord_profile_5.png" }, "text": "I want to see more of the Spinosaurus this time!" },
    { "author": { "name": "Cryolexis", "profile": "discord_profile_2.png" }, "text": "Right? That thing was a beast in Jurassic Park III!" },
    { "author": { "name": "GrandNerd", "profile": "discord_profile_3.png" }, "text": "They better not make another hybrid, we had enough." },
    { "author": { "name": "Blazing", "profile": "discord_profile_1.png" }, "text": "Agreed. Just give us the classics, no more experiments!" },
    { "author": { "name": "GrandNerd", "profile": "discord_profile_3.png" }, "text": "Do you think they’ll reference Camp Cretaceous: Chaos Theory?" },
    { "author": { "name": "Cryolexis", "profile": "discord_profile_2.png" }, "text": "They should! That show had some crazy dinosaur action." },
    { "author": { "name": "Spinosalad", "profile": "discord_profile_5.png" }, "text": "I just hope they don’t overuse CGI like last time." },
    { "author": { "name": "DinoDude32", "profile": "discord_profile_4.png" }, "text": "Yeah, practical effects make the dinosaurs feel more real!" },
    { "author": { "name": "Blazing", "profile": "discord_profile_1.png" }, "text": "The original T-Rex animatronic was terrifying, even today!" },
    { "author": { "name": "GrandNerd", "profile": "discord_profile_3.png" }, "text": "Imagine being on set with that thing staring at you." },
    { "author": { "name": "Spinosalad", "profile": "discord_profile_5.png" }, "text": "I’d probably run faster than the guy in the first movie!" },
    { "author": { "name": "Cryolexis", "profile": "discord_profile_2.png" }, "text": "Would you guys visit a real Jurassic World park?" },
    { "author": { "name": "Blazing", "profile": "discord_profile_1.png" }, "text": "No way! We all know how that end, lmao" },
    { "author": { "name": "DinoDude32", "profile": "discord_profile_4.png" }, "text": "I’d go, but only if I had a backup plan!" },
    { "author": { "name": "GrandNerd", "profile": "discord_profile_3.png" }, "text": "A backup plan? You mean running for your life?" },
    { "author": { "name": "Cryolexis", "profile": "discord_profile_2.png" }, "text": "If the fences go down, I’m out of there!" },
    { "author": { "name": "Spinosalad", "profile": "discord_profile_5.png" }, "text": "What if they finally learned from their mistakes?" },
    { "author": { "name": "Blazing", "profile": "discord_profile_1.png" }, "text": "You mean like they supposedly did every single time?" },
    { "author": { "name": "Cryolexis", "profile": "discord_profile_2.png" }, "text": "At this point, it’s tradition to have things go wrong!" },
    { "author": { "name": "DinoDude32", "profile": "discord_profile_4.png" }, "text": "I’d still love to see a Mosasaurus up close." },
    { "author": { "name": "Spinosalad", "profile": "discord_profile_5.png" }, "text": "Only if there’s a thick glass wall between us!" },
    { "author": { "name": "Cryolexis", "profile": "discord_profile_2.png" }, "text": "Yeah, no way I’m getting near that thing." },
    { "author": { "name": "GrandNerd", "profile": "discord_profile_3.png" }, "text": "Imagine it jumping out of the water like in the movies!" },
    { "author": { "name": "DinoDude32", "profile": "discord_profile_4.png" }, "text": "That’s why I stick to dinosaur museums, much safer." },
    { "author": { "name": "Cryolexis", "profile": "discord_profile_2.png" }, "text": "But way less exciting! I want real dinosaurs." },
    { "author": { "name": "Blazing", "profile": "discord_profile_1.png" }, "text": "And that’s how we get another Jurassic Park disaster!" },
    { "author": { "name": "Spinosalad", "profile": "discord_profile_5.png" }, "text": "Yeah, no way I’m getting near that thing." },
    { "author": { "name": "GrandNerd", "profile": "discord_profile_3.png" }, "text": "Imagine it jumping out of the water like in the movies!" },
];
